force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Repositories/DashboardRepository.cls
public class DashboardRepository {	 
        
    public static DashboardSummaryDto getDashboardSummary(){
        String approvedValue = 'Approved';
        String rejectedValue = 'Rejected';
        String referredValue = 'Referred';
        DashboardSummaryDto summaryDto = new DashboardSummaryDto();
        
        summaryDto.TotalLoans = database.countQuery('select count() from Loan__c');
        
        AggregateResult ar = [SELECT SUM(Amount__c) amount from Loan__c];
        summaryDto.TotalAmount = (Double)ar.get('amount');
        
        summaryDto.ApprovedLoans = database.countQuery('SELECT COUNT() from Loan__c where Status__c =:approvedValue');
        summaryDto.RejectedLoans = database.countQuery('SELECT COUNT() from Loan__c where Status__c =:rejectedValue');
        summaryDto.ReferredLoans = database.countQuery('SELECT COUNT() from Loan__c where Status__c =:referredValue');
        
        return summaryDto;
    }
}